# Generated by Django 4.2.16 on 2024-11-10 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0005_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reactors',
            field=models.ManyToManyField(blank=True, related_name='post_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='positive', max_length=8),
        ),
    ]
