# Generated by Django 4.2.16 on 2024-11-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_comment_reactors_alter_comment_comment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='positive', max_length=10),
        ),
    ]
