# Generated by Django 4.2.16 on 2024-11-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_comment_comment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['post_created_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='approved',
            new_name='comment_approved',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='comment_author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment_body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='comment_created_on',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='reactors',
            new_name='comment_reactors',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='comment_updated_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='parent_post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='post_author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='post_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='post_created_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='excerpt',
            new_name='post_excerpt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='featured_image',
            new_name='post_featured_image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='post_slug',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='post_status',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='post_title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_at',
            new_name='post_updated_at',
        ),
    ]
