# Generated by Django 4.2.16 on 2024-11-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_approved',
            field=models.BooleanField(default=True),
        ),
    ]
