# Generated by Django 4.2.16 on 2024-11-24 19:32

from django.conf import settings
from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0009_alter_comment_comment_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_created_on'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_created_on'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_approved',
            field=models.BooleanField(default=True, help_text='Whether the comment is approved for display'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=models.TextField(help_text='Content of the comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_reactors',
            field=models.ManyToManyField(blank=True, help_text='Users who have reacted to this comment', related_name='post_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='positive', help_text='Whether the comment is positive or negative', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(help_text='Main content of the post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_excerpt',
            field=models.TextField(blank=True, help_text='Brief summary of the post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(help_text='URL-friendly version of the title', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='0: Draft, 1: Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(help_text='Title of the post', max_length=200, unique=True, validators=[forum.models.validate_not_empty]),
        ),
    ]
