# Generated by Django 4.2.16 on 2024-11-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_comment_reactors_alter_comment_comment_type'),
        ('profiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiler',
            name='last_comments',
            field=models.ManyToManyField(blank=True, related_name='profile_comments', to='forum.comment'),
        ),
        migrations.AlterField(
            model_name='profiler',
            name='last_posts',
            field=models.ManyToManyField(blank=True, related_name='profile_posts', to='forum.post'),
        ),
    ]
