# Generated by Django 4.2.16 on 2024-11-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0002_alter_profiler_last_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiler',
            old_name='bio',
            new_name='profile_bio',
        ),
        migrations.RenameField(
            model_name='profiler',
            old_name='created_on',
            new_name='profile_created_on',
        ),
        migrations.RenameField(
            model_name='profiler',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.RenameField(
            model_name='profiler',
            old_name='last_comments',
            new_name='profile_last_comments',
        ),
        migrations.RenameField(
            model_name='profiler',
            old_name='last_posts',
            new_name='profile_last_posts',
        ),
        migrations.RenameField(
            model_name='profiler',
            old_name='updated_on',
            new_name='profile_updated_on',
        ),
        migrations.RenameField(
            model_name='profiler',
            old_name='user',
            new_name='profile_user',
        ),
    ]
