# Generated by Django 4.2.16 on 2024-11-24 15:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0003_rename_bio_profiler_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiler',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='static/images/default.png', max_length=255, verbose_name='image'),
        ),
    ]
