# Generated by Django 4.2.16 on 2024-11-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_content_about_about_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboraterequest',
            old_name='message',
            new_name='collaboration_message',
        ),
        migrations.RenameField(
            model_name='collaboraterequest',
            old_name='email',
            new_name='collaborator_email',
        ),
        migrations.RenameField(
            model_name='collaboraterequest',
            old_name='name',
            new_name='collaborator_name',
        ),
        migrations.RenameField(
            model_name='collaboraterequest',
            old_name='read',
            new_name='request_read',
        ),
    ]
